### ISSUE TITLE
Choose an Android development environment

### ISSUE THREAD

**Issue by daliborduric** [coremind-oss/ttasm-web-server#11]
...

**Comment by markog7** [comment]
I think that Android Studio is a good choice for Android environment.

**Comment by daliborduric** [comment]
can you provide links to examples and documentation?

**Comment by markog7** [comment]
https://developer.android.com/studio/features.html

**Comment by markog7** [comment]
It works with Java..maybe then [](http://qpython.com/#support) will be a better choice!

**Comment by markog7** [comment]
It works with Java..maybe then QPython will be a better choice!
[](http://qpython.com/#support)

**Comment by markog7** [comment]
http://qpython.com/#support

**Comment by daliborduric** [comment]
Frameworks: http://codecondo.com/top-12-frameworks-for-android-app-development/
Python: https://www.quora.com/Can-I-make-an-Android-app-with-Python

**Comment by Shortylo85** [comment]
Just checking pygame, and I think it's the best choice for our app. Not to hard for understanding and I'll start to play with it from tommorow.
