### ISSUE TITLE
Discuss which css framework we should use

### ISSUE THREAD

**Issue by Pekmen** [coremind-oss/ttasm-web-server#20]

**Comment by Shortylo85** [comment]
My opinion is that we should use bootstrap, it's most familiar with all of us and have large community for problems solving.

**Comment by Pekmen** [comment]
http://getbootstrap.com/

another option would be Skeleton, which is much more lightweight and doesn't come with so many components like Bootstrap (most of which we would not use anyway)

**Comment by Pekmen** [comment]
http://getskeleton.com/

**Comment by Shortylo85** [comment]
They all look almost same... Using prepared classes for getting work done.

**Comment by Pekmen** [comment]
the definition of css framework :)

**Comment by markog7** [comment]
you can always customize bootstrap to be lightweight and minimized.

**Comment by daliborduric** [comment]
http://materializecss.com/
http://foundation.zurb.com/

**Comment by daliborduric** [comment]
a really nice presentation from materialize https://themes.materializecss.com/pages/startup-horizontal-half.html

**Comment by Pekmen** [comment]
I've never used foundation but that looks sick. Definitely great for larger websites with a lots of components.

If we are going to make our project with clean design that also looks appealing, maybe materialize is the way to go.

**Comment by daliborduric** [comment]
https://themes.materializecss.com/pages/startup-postcard.html is very interesting as well if you didn't explore different pages

**Comment by LukaDjordjevic** [comment]
Top 10 Front-End Frameworks of 2016 with pros and cons
https://www.keycdn.com/blog/front-end-frameworks/

Also
https://www.sitepoint.com/5-most-popular-frontend-frameworks-compared/

**Comment by LukaDjordjevic** [comment]
Bootstrap vs foundation
https://www.keycdn.com/blog/bootstrap-vs-foundation/

**Comment by daliborduric** [comment]
we decided to use all the frameworks that people want to use by namespacing the framework name in ui/templates/**FRAMEWORK NAME**/**TEMPLATES**
