### ISSUE TITLE
Figure out timezone of a Desktop computer

### ISSUE THREAD

**Issue by daliborduric** [coremind-oss/ttasm-web-server#33]
based on the IP address, from which the user is logging in, figure out the timezone using http://ip-api.com/json/x.x.x.x

**Comment by daliborduric** [comment]
```
from pytz import timezone as tzinfo
eu_bg = tzinfo('Europe/Belgrade')

from django.utils import timezone
t = timezone.now()
t.astimezone(eu_bg)
```

**Comment by Shortylo85** [comment]
**After locating of desktop object via IP , and finding a current timezone of desktop object ( did it in show_timezone.py ), need some explanation where to put this function created in timezone.py. and where should be place for activating that kind of detection? Is it logic to be on desktop side of application after successfully submited form?**

**Comment by Shortylo85** [comment]
This is moved to desktop app
